### ISSUE TITLE
cov

### ISSUE THREAD

**Issue by johnros** [EfratVil/MultiNav#11]
https://github.com/EfratVil/MultiNav/blob/2d523ae15e433952578d113c5911498713cf3b62/man/T2.Rd#L12

be consistent with capitalization. Pearson is also a name. 
But you are mixing covariances with correlations. This is very confusing, even if it makes statistical sense (which I am not sure it does).

**Comment by EfratVil** [comment]
Ok. Went with low caps like in the stat pack.
