### ISSUE TITLE
reference

### ISSUE THREAD

**Issue by johnros** [EfratVil/MultiNav#12]
https://github.com/EfratVil/MultiNav/blob/2d523ae15e433952578d113c5911498713cf3b62/man/T2.Rd#L34

Is that a relevant reference here? Why are you not referencing Wilcox's robust statistics?

**Comment by EfratVil** [comment]
Montgomery ref for classic Hotelling T2.
The robust cov est ref is covered by the robustbase ref.

**Comment by johnros** [comment]
Montgomery very non standard for T2. 
Please use a different reference.

**Comment by EfratVil** [comment]
I saw other papers refer to:
HOTELLING, HAROLD. Multivariate quality control. Techniques of statistical analysis. McGraw-Hill, New York, 1947.‏
So I updated to this ref.
